GET http://localhost:3001/api/users HTTP/1.1
###
POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "name": "test",
    "password": "test"
}

###
POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVmYTE3MDczZTA4YjkxMGE1NWY3YjRkZiIsImlhdCI6MTYwNDQxNTc4MX0.jZuiH3eGliLpONem1YfRHqOl31UJ8u7OsFoE1LadIcI


{
    "title": "test2",
    "author": "Adam Smith",
    "url": "someurl.com",
    "likes": "10",
    "userId": "5fa17073e08b910a55f7b4df"
}

###
@id=5f7b3c44601bc916bbfc0ac5

DELETE  http://localhost:3003/api/blogs/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: bearer eJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkF3d2RhbW4iLCJpZCI6IjVmNzU5MWI4NzQzYjczMTBlYWIwOTUxMyIsImlhdCI6MTYwMTkwOTQ0MH0.rDM2jVyXtQBdvHplqK1P1QE7D2InvOCjIpVRE5a4LFU

###
POST http://localhost:3001/api/testing/reset HTTP/1.1

